services:
  proxy:
    build:
      context: ./proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/logs:/var/log/nginx
    networks:
      - sandbox

  api:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    command: npm i && node server.js
    networks:
      - sandbox

  db:
    build:
      context: ./db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sandbox

volumes:
  db-data:

networks:
  sandbox:

