services:
  proxy: 
    build: ./proxy
    volumes: 
     - ./proxy/logs:/var/log/nginx/
    networks:
      - sandbox
    ports:
      - 80:80
      - 443:443


  db:
    build: ./db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - sandbox
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "-qtAc", "SELECT 1;"]
      retries: 2
      start_period: 2s
      start_interval: 5s

  api:
    build: ./api
    depends_on: 
      db:
        condition: service_healthy
        restart: true
    networks:
      - sandbox
  
volumes:
  db-data:

networks:
  sandbox:
